xrobot/urls.py
from django.contrib import admin
from django.urls import path, include
from nix import views

urlpatterns = [
    path('tasks', views.tasks, name='tasks'),
    path('task/<int:tpk>', views.task, name='task'),
    path('task/create', views.task_create, name='task_create'),

    path('xperf/<int:tpk>/create', views.xperf_create, name='xperf_create'),
    path('xperf/<int:xpk>', views.xperf, name='xperf'),
    path('xperf/<int:xpk>/run', views.xperf_run, name='xperf_run'),
    path('xperf/<int:xpk>/stop', views.xperf_stop, name='xperf_stop'),

    path('admin/', admin.site.urls),
]

nix/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation   import ugettext_lazy as _

Auto_Perf_Settings = {
    'buffsize':['32k', '64k', '128k','256k','512k','1024k']
}


class Task(models.Model):
    '''针对某硬件设备创建测试任务'''
    STATUS=(
        (0, _('Created')),
        (1, _('Running')),
        (2, _('Error/Suspend')),
        (3, _('Success')),
    )

    MODE = (
        (0, 'Auto Perf'),
        (1, 'Custome')
    )

    name    = models.CharField(max_length=100, verbose_name='Task Name')
    mode    = models.PositiveIntegerField(_("Mode"))
    creator = models.ForeignKey(User, related_name='Creator', on_delete=models.CASCADE)
    status  = models.PositiveIntegerField(verbose_name='Status', choices=STATUS, default=0)
    device  = models.CharField(max_length=100, verbose_name='Device')
    description = models.CharField(max_length=5000, verbose_name='Description')
    create_time = models.DateTimeField(_('Create time'),auto_now_add=True)

    class Meta:
        verbose_name = _("Task")
        verbose_name_plural = _("Tasks")

    def __str__(self):
        return '{}: {}'.format(self.device, self.name)

    def get_absolute_url(self):
        return reverse("Task_detail", kwargs={"pk": self.pk})


class XperfAbstractModel(models.Model):
    task= models.ForeignKey(Task, related_name='Task', on_delete=models.CASCADE)
    ip  = models.GenericIPAddressField(_("IP Address"),)
    port= models.PositiveIntegerField(_("Port"),)
    create_time = models.DateTimeField(_("Create Time"),auto_now_add=True)
    start_time  = models.DateTimeField(_("Start Time"),auto_now_add=False, null=True, blank=True)
    Stop_time   = models.DateTimeField(_("Stop Time"),auto_now_add=True)

    class Meta:
        abstract = True


class Xperf(XperfAbstractModel):
    SIZE = (
        (32, '32k'),
        (64, '64k'),
        (128, '128k'),
        (256, '256k'),
        (512, '512k'),
        (1024, '1024k'),
    )

    buff= models.PositiveIntegerField(_("Buff Size"), )
    parallel= models.PositiveIntegerField(_("Parallel"),)
    interval= models.PositiveIntegerField(_("Interval"), )
    seconds = models.PositiveIntegerField(_("seconds"),)
    

    class Meta:
        verbose_name = _("xperf")
        verbose_name_plural = _("xperfs")
    
    #@property
    def bootstrap(self):
        print('///////////')
        boots = 'iperf3 -c {} -p {} -w {}k -P {} -i {} -t {}'.format(self.ip, self.port, self.buff, self.parallel, self.interval, self.seconds)
        print(boots)
        #print(type(self.port), type(self.buff), type(self.interval), type(self.parallel), type(self.seconds), type(self.ip))
        return boots

    def __str__(self):
        return 'Task:{} / Xperf: {}:{}'.format(self.task, self.ip, self.port)

    def get_absolute_url(self):
        return reverse("xperf_detail", kwargs={"pk": self.pk})


    def run(self):
        res =  os.popen(self.bootstrap() +'|grep -E \'SUM|sec\'|tail -1|awk -F \']\' \'{ print $2}\'|awk \'{ print $5} \'').read().strip()
        return res

    def auto_run(self):
        return

    def stop(self):
        pid = os.popen('ps -ef|grep '+self.bootstrap()+'|awk \'{ print $2}\'').read().strip('\n').strip()
        os.system('kill -9 '+pid)
        return 



# class AutoPerf(XperfAbstractModel):
#     def __init__(self, *args, **kwargs):
#         self.ip = kwargs.pop('ip')
#         self.port = kwargs.pop('port')
#         self.buff = kwargs.pop('buff')
#         self.parallel = kwargs.pop('parallel')


class Perf(models.Model):
    xperf = models.ForeignKey(Xperf, related_name='Xperf', on_delete=models.CASCADE)
    result= models.FloatField(_("Result"))
    time_stamp  = models.DateTimeField(_("Time Stamp"), auto_now=True)
    

    class Meta:
        verbose_name = _("Perf")
        verbose_name_plural = _("Perfs")

    def __str__(self):
        return '{}: {}'.format(self.xperf, self.result)

    def get_absolute_url(self):
        return reverse("Perf_detail", kwargs={"pk": self.pk})

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <title>{% block title %} {{ title }} {% endblock title %}</title>
    <link href="{% static 'base/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'general/header.css' %}" >
    {% block css_conf %}
    
    
    {% endblock css_conf %}
    {% block js_conf %}  {% endblock js_conf %}
    
    
</head>
<body>
<div id='main'>
    {% block content %}{% endblock content %}
    
</div>
{% block javascript %} 
 
{% endblock javascript %}
<script>
    // 当页面内容小于桌面窗口时，把footer 固定在底部
    if(document.body.clientHeight<= window.screen.height)
    {
        document.getElementById("footer").style.position="fixed";  
    }
</script>
</body>

</html>

templates/task.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" >
{% endblock css_conf %}

{% block content %}
<style>
    @media screen and (min-width: 500px) {
           #main {
               width: 100%;
               min-width: 500px;
               background-color:rgb(243, 136, 30);
           }
       }

   @media screen and (max-width: 900px) {
           #main {
           width: 80%;
           margin-left: 10%;
           background-color: rgb(204, 246, 15);
       }
   }
   @media screen and (min-width: 1200px) {
       #main {
           width: 60%;
           margin-left: 20%;
           background-color: bisque;
           box-shadow: black;
           box-sizing: border-box;
       }
   }

   #title {
       text-align: center;
       font-size: xx-large;
       
   }
   h1 {
        margin: 0 auto;
   }


   #relations {
       width: 100%;
       margin: 1rem 5%;
       display: inline-flex; 
   }

   #xperf {
       width: 30%;
       display: inline-flex;
       margin-top: 1rem;
   }

   #xperf a {
        padding: 0 0.5rem;
   }


   #friends h1 {
      
       padding-left: -3rem;
       
   }

   #followers {
       width: 30%;
       padding: 0 0.5rem;
   }

   #following {
       width: 30%;
       padding: 0 0.5rem;
   }

</style>

<h1 style="text-align: center;"> TASK </h1>

<h2>{{ task }}</h2>

{% for xpf in xperfs %}

<div id=xperf style="display: inline;">
    <h3>{{ xpf }}</h3>| <a href="{% url 'xperf_run'  xpf.pk %}"> 执行 </a>
</div>

{% empty %}
   <h5>当前无Iperf 测试任务</h5>
{% endfor %}

<a href="{% url 'xperf_create' task.pk %}">创建iPerf 任务</a>

{% endblock content %}

templates/task_create.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/cat_create.css' %}" >
{% endblock css_conf %}

{% block content %}
<style>
    @media screen and (min-width: 500px) {
           #main {
               width: 100%;
               min-width: 500px;
               background-color:rgb(243, 136, 30);
           }
       }

   @media screen and (max-width: 900px) {
           #main {
           width: 80%;
           margin-left: 10%;
           background-color: rgb(204, 246, 15);
       }
   }
   @media screen and (min-width: 1200px) {
       #main {
           width: 60%;
           margin-left: 20%;
           background-color: bisque;
           box-shadow: black;
           box-sizing: border-box;
       }
   }
   </style>
   
<header>
    <h1>创建Task</h1>
    </header>
    <form action="" method="post" >{% csrf_token %}
        {{ form.as_p }}
        <!-- {{ form.non_field_errors }}
            <label for="{{ form.name.id_for_label }}"><strong>Task Name</strong> </label><br />
                <small id="emailHelp" class="form-text text-muted">Task's name</small><br />
                {{ form.name }} {{ form.name.errors }}
                <br /><br />
            <label for="{{ form.mode.id_for_label }}"><strong>Mode</strong> </label><br />
            
            {{ form.mode }} {{ form.mode.errors }}
            <br />
            <label for="{{ form.device.id_for_label }}"><strong>Device</strong> </label><br />
            
            {{ form.device }} {{ form.device.errors }}
            <br />

            <label for="{{ form.bio.id_for_label }}"><strong>简介</strong></label><br />
            <small id="emailHelp" >The Description about the catalog.</small><br />
            {{ form.description }} {{ form.description.errors }}
            <br /> -->
        <a href="#" class="button" onClick="javascript:history.back(-1);">返回</a>
        <input type="submit" value='Create' class="button">
    </form>
    

{% endblock content %}

templates/task_stop.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" >
{% endblock css_conf %}

{% block content %}

<h1 style="text-align: center;"> TASK </h1>

Status : Stop

<a href="{% url 'task_stop' task.pk %}">开始</a>

{% endblock content %}

templates/tasks.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" >
{% endblock css_conf %}

{% block content %}

TASKS<br />
<hr />
<a href="{% url 'task_create' %}"> 创建 Task </a>
{% for task in tasks %}

    <a href="{% url 'task' task.pk %}">{{ task }}</a>
{% endfor %}



{% endblock content %}

templates/xperf.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" >
{% endblock css_conf %}

{% block content %}
<style>
    @media screen and (min-width: 500px) {
           #main {
               width: 100%;
               min-width: 500px;
               background-color:rgb(243, 136, 30);
           }
       }

   @media screen and (max-width: 900px) {
           #main {
           width: 80%;
           margin-left: 10%;
           background-color: rgb(204, 246, 15);
       }
   }
   @media screen and (min-width: 1200px) {
       #main {
           width: 60%;
           margin-left: 20%;
           background-color: bisque;
           box-shadow: black;
           box-sizing: border-box;
       }
   }

   #title {
       text-align: center;
       font-size: xx-large;
       
   }
   h1 {
        margin: 0 auto;
   }


   #relations {
       width: 100%;
       margin: 1rem 5%;
       display: inline-flex; 
   }

   #xperf {
       width: 30%;
       display: inline-flex;
       margin-top: 1rem;
   }

   #xperf a {
        padding: 0 0.5rem;
   }


   #friends h1 {
      
       padding-left: -3rem;
       
   }

   #followers {
       width: 30%;
       padding: 0 0.5rem;
   }

   #following {
       width: 30%;
       padding: 0 0.5rem;
   }

</style>

<h1 style="text-align: center;"> XPERF </h1>

<div style="display:inline-block">
<h2>{{ xperf }}</h2>

<a href="{% url 'xperf_run'  xperf.pk %}"> 执行 </a>

</div>
{% endblock content %}

templates/xperf_create.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/cat_create.css' %}" >
{% endblock css_conf %}

{% block content %}
<style>
    @media screen and (min-width: 500px) {
           #main {
               width: 100%;
               min-width: 500px;
               background-color:rgb(243, 136, 30);
           }
       }

   @media screen and (max-width: 900px) {
           #main {
           width: 80%;
           margin-left: 10%;
           background-color: rgb(204, 246, 15);
       }
   }
   @media screen and (min-width: 1200px) {
       #main {
           width: 60%;
           margin-left: 20%;
           background-color: bisque;
           box-shadow: black;
           box-sizing: border-box;
       }
   }
   #id_buff {
        ime-mode: disabled;
    }
   </style>


    <header>
        <h1>iPerf 参数配置</h1>
    </header>
    <form action="" method="post" >{% csrf_token %}
        {{ form.as_p }}

        <a href="#" class="button" onClick="javascript:history.back(-1);">返回</a>
        <input type="submit" value='Create' class="button">
    </form>
    

{% endblock content %}

templates/xperf_run.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" >
{% endblock css_conf %}

{% block content %}
<style>
  #xperf {
      text-align: center;
  }

</style>


<div id=xperf>
    <h1 > Xperf Runing </h1>
    <h2> {{ boots }} </h2>
    <h3>Create Time : {{ create_time }}</h3>
    <br />
     <h1> {{ status }}</h1>
    <br />
    <a href="{% url 'xperf_stop' xperf.pk %}">停止</a>
</div>

{% endblock content %}

templates/xperf_stop.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css_conf %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" >
{% endblock css_conf %}

{% block content %}
<style>
  #xperf {
      text-align: center;
  }

</style>


<div id=xperf>
    <h1 > Xperf Runing </h1>
    <h2> {{ boots }} </h2>
    <h3>Create Time : {{ create_time }}</h3>
    <br />
     <h1> {{ status }}</h1>
    <br />
    <a href="{% url 'xperf_run' xperf.pk %}">Start</a>
</div>

{% endblock content %}